import argparse

parser = argparse.ArgumentParser(description='AsymmetricVAD')
parser.add_argument('--seed', default=234, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--attn-window', default=64, type=int)
parser.add_argument('--classes-num', default=7, type=int)
parser.add_argument('--similarity-threshold', default=0.35, type=float)
parser.add_argument('--lookback-steps', default=3, type=int)
parser.add_argument('--sie-window-radius', default=2, type=int)
parser.add_argument('--sie-topk-ratio', default=0.17, type=float)
parser.add_argument('--sie-sigma', default=3.0, type=float)
parser.add_argument('--sie-alpha-init', default=0.5, type=float)
parser.add_argument('--sie-epsilon-audio-init', default=0.1, type=float)
parser.add_argument('--sie-lambda-audio-init', default=0.1, type=float)
parser.add_argument('--uncertainty-threshold', default=0.4, type=float)

parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='model/model_xd.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='model/checkpoint.pth')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--train-list', default='list/xd_CLIP_rgb.csv')
parser.add_argument('--test-list', default='list/xd_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='list/gt.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment.npy')
parser.add_argument('--gt-label-path', default='list/gt_label.npy')
parser.add_argument('--category-text-path', default='list/category_text_xd.npy')

parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 6, 10])